version: "3.8"

services:
  app:
    depends_on:
      - api
    build: ./app
    ports:
      - 3000:3000

  api:
#    depends_on:
#      - database
    build: ./api
    ports:
      - 8999:8999
#    volumes:
#      - coffee_break:/api/database/data/
#
#  database:
#    image: keinos/sqlite3
#    volumes:
#      - coffee_break:/database/data/
#    ports:
#      - 3306:3306
#
#volumes:
#  coffee_break:
